const TOOLS=[{id:'quote',cat:'거래 · 금전',title:'견적서',desc:'유효기간·납기·결제조건 포함.',hot:true},{id:'receipt',cat:'거래 · 금전',title:'간이영수증',desc:'한글 금액 자동 표기.',hot:true},{id:'statement',cat:'거래 · 금전',title:'거래명세서',desc:'공급가액·세액 분리.',hot:false},{id:'approval',cat:'결재 · 지출',title:'품의서',desc:'기안·예산·결재란.',hot:true},{id:'leave',cat:'인사 · 근태',title:'휴가신청서',desc:'일수 자동 계산.',hot:true},{id:'salary',cat:'급여 · 세금',title:'연봉 실수령액 계산기',desc:'2026년 요율 4대보험·소득세.',hot:true},{id:'age',cat:'계산기',title:'만 나이 계산기',desc:'만·세는·연 나이.',hot:true},{id:'annual',cat:'계산기',title:'연차 계산기',desc:'입사일 기준 연차.',hot:true},{id:'severance',cat:'계산기',title:'퇴직금 계산기',desc:'재직일수·평균임금.',hot:true},{id:'stamp',cat:'도장 · 서명',title:'도장 만들기',desc:'원형 도장 PNG.',hot:false},{id:'charcount',cat:'계산기',title:'글자수 세기',desc:'공백 포함·제외.',hot:false},{id:'dutch',cat:'계산기',title:'회식비 N분의 1',desc:'1인당·올림.',hot:false}];
const CATS=['전체',...Array.from(new Set(TOOLS.map(t=>t.cat)))];
let current='home', activeCat='전체';
function n(v){const x=Number(String(v).replace(/[^\d.-]/g,''));return Number.isFinite(x)?x:0}
function won(v){return n(v).toLocaleString('ko-KR')}
function hangul(num){num=Math.floor(Math.abs(n(num)));if(!num)return '영원정';const small=['','일','이','삼','사','오','육','칠','팔','구'],unit=['','십','백','천'],big=['','만','억','조'];let s='',p=0;while(num>0){let chunk=num%10000,cs='';for(let i=0;i<4;i++){const d=chunk%10;if(d)cs=small[d]+unit[i]+cs;chunk=Math.floor(chunk/10)}if(cs)s=cs+big[p]+s;num=Math.floor(num/10000);p++}return '금'+s.replace(/일십/g,'십')+'원정'}
function today(){const d=new Date();return d.getFullYear()+'년 '+(d.getMonth()+1)+'월 '+d.getDate()+'일'}
function daysBetween(a,b){const d1=new Date(a),d2=new Date(b);if(isNaN(d1)||isNaN(d2))return 0;return Math.round((d2-d1)/86400000)}
function renderHome(){document.getElementById('cats').innerHTML=CATS.map(c=>`<button class="${c===activeCat?'on':''}" onclick="activeCat='${c}';filterCards()">${c}</button>`).join('');const q=(document.getElementById('q').value||'').trim();const groups={};TOOLS.filter(t=>(activeCat==='전체'||t.cat===activeCat)&&(!q||t.title.includes(q)||t.desc.includes(q))).forEach(t=>{(groups[t.cat]=groups[t.cat]||[]).push(t)});document.getElementById('lists').innerHTML=Object.keys(groups).map(cat=>`<h3>${cat}</h3><div class="grid">${groups[cat].map(t=>`<div class="card" onclick="go('${t.id}')"><b>${t.title}${t.hot?'<span class="badge">인기</span>':''}</b><span>${t.desc}</span></div>`).join('')}</div>`).join('')||'<p class="hint">검색 결과가 없습니다.</p>'}
function filterCards(){renderHome()}
function go(id){current=id;const home=document.getElementById('home'),app=document.getElementById('app'),actions=document.getElementById('toolActions');if(id==='home'){home.classList.add('show');app.classList.remove('show');actions.classList.remove('show');document.getElementById('crumb').textContent='도구 바로가기';renderHome();return}home.classList.remove('show');app.classList.add('show');actions.classList.add('show');const t=TOOLS.find(x=>x.id===id);document.getElementById('crumb').textContent=t?t.title:id;document.getElementById('formTitle').textContent=(t?t.title:'도구')+' 내용 입력';buildForm(id);render()}
function field(id,label,val='',ph=''){return `<label>${label}</label><input id="${id}" value="${val}" placeholder="${ph}" oninput="render()" />`}
function area(id,label,val=''){return `<label>${label}</label><textarea id="${id}" oninput="render()">${val}</textarea>`}
function val(id){const el=document.getElementById(id);return el?el.value:''}
function itemTable(rows=4){let h='<table class="items"><thead><tr><th>품명</th><th>규격</th><th>수량</th><th>단가</th><th></th></tr></thead><tbody id="itemBody">';for(let i=0;i<rows;i++)h+=`<tr><td><input class="iname" oninput="render()"></td><td><input class="ispec" oninput="render()"></td><td><input class="iqty" value="${i===0?1:''}" oninput="render()"></td><td><input class="iprice" oninput="render()"></td><td><button class="btn" onclick="this.closest('tr').remove();render()">✕</button></td></tr>`;return h+'</tbody></table><button class="btn" style="margin-top:8px" onclick="addRow()">품목 추가</button>'}
function addRow(){const tr=document.createElement('tr');tr.innerHTML='<td><input class="iname" oninput="render()"></td><td><input class="ispec" oninput="render()"></td><td><input class="iqty" oninput="render()"></td><td><input class="iprice" oninput="render()"></td><td><button class="btn" onclick="this.closest(\'tr\').remove();render()">✕</button></td>';document.getElementById('itemBody').appendChild(tr)}
function collectItems(){return [...document.querySelectorAll('#itemBody tr')].map(tr=>({name:tr.querySelector('.iname')?.value||'',spec:tr.querySelector('.ispec')?.value||'',qty:n(tr.querySelector('.iqty')?.value),price:n(tr.querySelector('.iprice')?.value)})).filter(x=>x.name||x.price)}
function saveCompany(){const keys=['bizno','corp','ceo','tel','addr','uptae','jongmok','staff','stafftel'];const o={};keys.forEach(k=>o[k]=val(k));localStorage.setItem('kaltoe-co',JSON.stringify(o));alert('이 브라우저에 저장했습니다.')}
function loadCompany(){try{return JSON.parse(localStorage.getItem('kaltoe-co')||'{}')}catch(e){return {}}}
function companyFields(){const c=loadCompany();return `<b>공급자</b><div class="row2">${field('bizno','사업자등록번호',c.bizno||'123-45-67890')}${field('corp','상호',c.corp||'한빛산업')}</div><div class="row2">${field('ceo','대표자',c.ceo||'홍길동')}${field('tel','연락처',c.tel||'02-123-4567')}</div>${field('addr','사업장',c.addr||'서울특별시 마포구')}<div class="row2">${field('uptae','업태',c.uptae||'제조·도소매')}${field('jongmok','종목',c.jongmok||'사무기기')}</div><button class="btn" style="margin-top:10px" onclick="saveCompany()">이 정보 기억하기</button>`}
function buildForm(id){const f=document.getElementById('formBody');
if(id==='quote')f.innerHTML=companyFields()+`${field('recv','수신 상호','주식회사 미래')}${field('no','문서번호','Q-2026-091')}<div class="row2">${field('valid','유효기간','30일')}${field('due','납기','협의')}</div><div class="row2">${field('pay','결제조건','30일')}${field('place','인도장소','지정 장소')}</div><label>품목</label>${itemTable(4)}${area('note','비고','상기와 같이 견적합니다.')}`;
else if(id==='receipt')f.innerHTML=companyFields()+`${field('recv','공급받는 자','')}${field('reason','공급 내용','물품 대금')}${field('amt','영수 금액','150000')}<label><input type="checkbox" id="vatinc" checked onchange="render()" /> 부가세 포함</label>`;
else if(id==='statement')f.innerHTML=companyFields()+`${field('recv','공급받는 자','주식회사 미래')}${field('no','문서번호','S-2026-014')}<label>품목</label>${itemTable(5)}`;
else if(id==='approval')f.innerHTML=`${field('dept','기안부서','영업팀')}${field('drafter','기안자','김장우')}${field('title','제목','병원 인테리어 자재 발주 품의')}${area('body','내용','자재 발주를 품의합니다.')}${field('budget','소요예산','8500000')}${field('line','결재선','담당,팀장,대표')}`;
else if(id==='leave')f.innerHTML=`${field('name','신청자','김장우')}${field('dept','부서','디자인팀')}<label>휴가 종류</label><select id="kind" onchange="render()"><option>연차</option><option>반차(오전)</option><option>반차(오후)</option></select><div class="row2">${field('from','시작일',new Date().toISOString().slice(0,10))}${field('to','종료일',new Date().toISOString().slice(0,10))}</div>${field('agent','업무대행자','')}${area('why','사유','개인 사정')}`;
else if(id==='salary')f.innerHTML=`${field('annual','연봉 (원)','48000000')}${field('non','비과세 월','200000')}${field('dep','부양가족 수','1')}`;
else if(id==='age')f.innerHTML=`${field('birth','생년월일','1993-06-09')}${field('base','기준일',new Date().toISOString().slice(0,10))}`;
else if(id==='annual')f.innerHTML=`${field('join','입사일','2020-03-01')}${field('base','기준일',new Date().toISOString().slice(0,10))}`;
else if(id==='severance')f.innerHTML=`${field('join','입사일','2019-04-01')}${field('out','퇴직일',new Date().toISOString().slice(0,10))}${field('avg','평균임금 월','3800000')}`;
else if(id==='stamp')f.innerHTML=`${field('s1','윗줄','한빛산업')}${field('s2','아랫줄','대표이사인')}<label>색</label><input type="color" id="scolor" value="#c81e1e" oninput="render()" />`;
else if(id==='charcount')f.innerHTML=area('txt','텍스트','');
else if(id==='dutch')f.innerHTML=`${field('total','총액','186000')}${field('people','인원','7')}${field('unit','올림 단위','1000')}`}
function fillExample(){if(current==='quote'){const rows=document.querySelectorAll('#itemBody tr');[['LVT 바닥재','2.0T','80','42000'],['페인트','18L','12','38000'],['LED','30W','24','27000']].forEach((s,i)=>{if(!rows[i])return;rows[i].querySelector('.iname').value=s[0];rows[i].querySelector('.ispec').value=s[1];rows[i].querySelector('.iqty').value=s[2];rows[i].querySelector('.iprice').value=s[3]})}render()}
function resetTool(){buildForm(current);render()}
function taxEstimate(monthlyTaxable,dependents){const annual=monthlyTaxable*12;let earnedDeduct;if(annual<=5e6)earnedDeduct=annual*.7;else if(annual<=15e6)earnedDeduct=3.5e6+(annual-5e6)*.4;else if(annual<=45e6)earnedDeduct=7.5e6+(annual-15e6)*.15;else if(annual<=1e8)earnedDeduct=12e6+(annual-45e6)*.05;else earnedDeduct=14.75e6+(annual-1e8)*.02;const base=Math.max(0,annual-earnedDeduct-1.5e6*Math.max(1,dependents));const brackets=[[14e6,.06],[36e6,.15],[88e6,.24],[150e6,.35],[300e6,.38],[500e6,.4],[1e9,.42],[Infinity,.45]];let remain=base,prev=0,tax=0;for(const [lim,rate] of brackets){const span=Math.min(remain,lim-prev);if(span<=0)break;tax+=span*rate;remain-=span;prev=lim}let credit=tax<=1.3e6?tax*.55:715000+(tax-1.3e6)*.3;credit=Math.min(credit,740000);const income=Math.max(0,Math.round((tax-credit)/12));return {income,local:Math.round(income*.1)}}
function render(){const p=document.getElementById('paper');
if(current==='quote'||current==='statement'){const items=collectItems();const supply=items.reduce((s,i)=>s+i.qty*i.price,0);const vat=Math.round(supply*.1),total=supply+vat;const rows=items.map((i,idx)=>`<tr><td>${idx+1}</td><td>${i.name}</td><td>${i.spec}</td><td style="text-align:right">${i.qty}</td><td style="text-align:right">${won(i.price)}</td><td style="text-align:right">${won(i.qty*i.price)}</td></tr>`).join('');const title=current==='quote'?'견 적 서':'거래명세서';p.innerHTML=`<div class="doc-title">${title}</div><div class="meta"><span>No. ${val('no')||'-'}</span><span>${today()}</span></div><div style="text-align:center;margin:8px 0 14px">${val('recv')||'(수신)'} <b>귀중</b></div><table class="doc"><tr><th>등록번호</th><td colspan="3">${val('bizno')}</td></tr><tr><th>상호</th><td>${val('corp')}</td><th>성명</th><td>${val('ceo')} (인)</td></tr><tr><th>사업장</th><td colspan="3">${val('addr')}</td></tr></table><div class="sum-box"><div>합계 <b>${hangul(total)}</b></div><div>₩ ${won(total)}</div></div>${current==='quote'?`<table class="doc" style="margin-bottom:10px"><tr><th>유효기간</th><td>${val('valid')}</td><th>납기</th><td>${val('due')}</td></tr><tr><th>결제</th><td>${val('pay')}</td><th>인도</th><td>${val('place')}</td></tr></table>`:''}<table class="doc"><tr><th>No</th><th>품명</th><th>규격</th><th>수량</th><th>단가</th><th>금액</th></tr>${rows}<tr><th colspan="5">공급가액</th><td style="text-align:right">${won(supply)}</td></tr><tr><th colspan="5">부가세</th><td style="text-align:right">${won(vat)}</td></tr><tr><th colspan="5">합계</th><td style="text-align:right">${won(total)}</td></tr></table><p style="margin-top:16px;font-size:12px">${val('note')}</p>`}
else if(current==='receipt'){const amt=n(val('amt'));const vatinc=document.getElementById('vatinc')?.checked;const supply=vatinc?Math.round(amt/1.1):amt;const vat=vatinc?amt-supply:Math.round(amt*.1);const total=vatinc?amt:amt+vat;p.innerHTML=`<div class="doc-title">간 이 영 수 증</div><p style="text-align:right;font-size:12px">${today()}</p><table class="doc"><tr><th>공급받는 자</th><td>${val('recv')||'-'}</td></tr><tr><th>공급자</th><td>${val('corp')} (${val('ceo')})</td></tr><tr><th>사업자등록번호</th><td>${val('bizno')}</td></tr><tr><th>공급 내용</th><td>${val('reason')}</td></tr><tr><th>합계</th><td><b>${won(total)}원</b><br>${hangul(total)}</td></tr></table><p style="margin-top:24px;text-align:center">위 금액을 정히 영수합니다.</p>`}
else if(current==='approval'){const line=val('line').split(',').map(s=>s.trim()).filter(Boolean);p.innerHTML=`<div class="doc-title">품 의 서</div><table class="doc"><tr><th>기안부서</th><td>${val('dept')}</td><th>기안자</th><td>${val('drafter')}</td></tr><tr><th>제목</th><td colspan="3">${val('title')}</td></tr><tr><th>소요예산</th><td colspan="3">${won(val('budget'))}원</td></tr><tr><td colspan="4" style="height:220px;vertical-align:top;white-space:pre-wrap">${val('body')}</td></tr></table><table class="doc" style="margin-top:16px"><tr>${line.map(x=>`<th>${x}</th>`).join('')}</tr><tr>${line.map(()=>'<td style="height:72px"></td>').join('')}</tr></table>`}
else if(current==='leave'){const kind=val('kind');let days=daysBetween(val('from'),val('to'))+1;if(kind.includes('반차'))days=.5;p.innerHTML=`<div class="doc-title">휴 가 신 청 서</div><table class="doc"><tr><th>신청자</th><td>${val('name')}</td><th>부서</th><td>${val('dept')}</td></tr><tr><th>종류</th><td>${kind}</td><th>일수</th><td>${days}일</td></tr><tr><th>기간</th><td colspan="3">${val('from')} ~ ${val('to')}</td></tr><tr><th>사유</th><td colspan="3">${val('why')}</td></tr></table>`}
else if(current==='salary'){const annual=n(val('annual')),month=Math.round(annual/12),nontax=n(val('non')),dep=Math.max(1,n(val('dep')));const base=Math.max(0,month-nontax);const np=Math.floor(Math.min(6370000,Math.max(400000,base))*0.0475);const hi=Math.round(base*0.03595),lt=Math.round(hi*0.1314),ei=Math.round(base*0.009);const ins=np+hi+lt+ei;const {income,local}=taxEstimate(base-ins,dep);const take=month-ins-income-local;p.innerHTML=`<div class="doc-title" style="letter-spacing:.15em">연봉 실수령액</div><div class="big-num">월 ${won(take)}원</div><div class="calc-row"><span>세전 월급</span><b>${won(month)}</b></div><div class="calc-row"><span>국민연금</span><b>- ${won(np)}</b></div><div class="calc-row"><span>건강보험</span><b>- ${won(hi)}</b></div><div class="calc-row"><span>장기요양</span><b>- ${won(lt)}</b></div><div class="calc-row"><span>고용보험</span><b>- ${won(ei)}</b></div><div class="calc-row"><span>소득세(추정)</span><b>- ${won(income)}</b></div><div class="calc-row"><span>지방소득세</span><b>- ${won(local)}</b></div><div class="calc-row total"><span>월 실수령액</span><b>${won(take)}</b></div>`}
else if(current==='age'){const birth=new Date(val('birth')),base=new Date(val('base'));if(isNaN(birth)||isNaN(base)){p.innerHTML='날짜를 확인하세요.';return}let man=base.getFullYear()-birth.getFullYear();const md=base.getMonth()-birth.getMonth();if(md<0||(md===0&&base.getDate()<birth.getDate()))man--;p.innerHTML=`<div class="big-num">만 ${man}세</div><div class="calc-row"><span>세는 나이</span><b>${base.getFullYear()-birth.getFullYear()+1}세</b></div>`}
else if(current==='annual'){const join=new Date(val('join')),base=new Date(val('base'));if(isNaN(join)||isNaN(base)){p.innerHTML='날짜를 확인하세요.';return}const months=(base.getFullYear()-join.getFullYear())*12+(base.getMonth()-join.getMonth());let days=0;if(months<12)days=Math.floor(((base-join)/86400000)/30.42);else{days=15+Math.floor((Math.floor(months/12)-1)/2);if(days>25)days=25}p.innerHTML=`<div class="big-num">${days}일</div><div class="calc-row"><span>근속</span><b>${Math.floor(months/12)}년 ${months%12}개월</b></div>`}
else if(current==='severance'){const join=new Date(val('join')),out=new Date(val('out')),avg=n(val('avg'));const days=Math.max(0,Math.round((out-join)/86400000)+1);const years=days/365;const pay=years>=1?Math.round(avg*years):0;p.innerHTML=`<div class="big-num">${won(pay)}원</div><div class="calc-row"><span>재직일수</span><b>${days}일</b></div>`}
else if(current==='stamp'){p.innerHTML='<canvas id="stampcv" width="360" height="360" style="display:block;margin:20px auto"></canvas><p style="text-align:center"><button class="btn dark" onclick="dlStamp()">PNG 저장</button></p>';const cv=document.getElementById('stampcv'),ctx=cv.getContext('2d'),color=val('scolor')||'#c81e1e';ctx.clearRect(0,0,360,360);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=10;ctx.beginPath();ctx.arc(180,180,150,0,Math.PI*2);ctx.stroke();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='700 34px Pretendard,sans-serif';ctx.fillText(val('s1')||'상호',180,150);ctx.font='700 28px Pretendard,sans-serif';ctx.fillText(val('s2')||'인',180,210)}
else if(current==='charcount'){const t=val('txt');p.innerHTML=`<div class="calc-row"><span>공백 포함</span><b>${t.length}</b></div><div class="calc-row"><span>공백 제외</span><b>${t.replace(/\s/g,'').length}</b></div>`}
else if(current==='dutch'){const total=n(val('total')),people=Math.max(1,n(val('people'))),unit=Math.max(1,n(val('unit')));const each=Math.ceil(total/people/unit)*unit;p.innerHTML=`<div class="big-num">1인 ${won(each)}원</div><div class="calc-row"><span>총무 잔액</span><b>${won(each*people-total)}</b></div>`}}
function dlStamp(){const a=document.createElement('a');a.href=document.getElementById('stampcv').toDataURL('image/png');a.download='stamp.png';a.click()}
renderHome();
